"""initial schema

Revision ID: c1d62e84e9e0
Revises: 
Create Date: 2026-04-29 20:19:20.155855

"""
from alembic import op
import sqlalchemy as sa


revision = 'c1d62e84e9e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caldav_username', sa.String(length=200), nullable=True),
    sa.Column('caldav_password_enc', sa.Text(), nullable=True),
    sa.Column('caldav_calendar_name', sa.String(length=100), nullable=False),
    sa.Column('caldav_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weekly_totals_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_week_start'), ['week_start'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('default_unit', sa.String(length=16), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('typical_pack_size_g', sa.Float(), nullable=True),
    sa.Column('est_price_chf', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('off_barcode', sa.String(length=32), nullable=True),
    sa.Column('off_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name_normalized'), ['name_normalized'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_off_barcode'), ['off_barcode'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whitelist_json', sa.JSON(), nullable=False),
    sa.Column('blacklist_json', sa.JSON(), nullable=False),
    sa.Column('fitness_goal', sa.String(length=32), nullable=False),
    sa.Column('kcal_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Integer(), nullable=False),
    sa.Column('max_prep_min', sa.Integer(), nullable=False),
    sa.Column('weekly_budget_chf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diet_tags_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_history_date'), ['date'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('prep_time_min', sa.Integer(), nullable=False),
    sa.Column('macros_json', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_chf', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('uses_leftovers_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uses_leftovers_from_id'], ['meals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_plan_id'), ['plan_id'], unique=False)

    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_ingredients_meal_id'), ['meal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_ingredients_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_ingredients_product_id'))
        batch_op.drop_index(batch_op.f('ix_meal_ingredients_meal_id'))

    op.drop_table('meal_ingredients')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_plan_id'))
        batch_op.drop_index(batch_op.f('ix_meals_date'))

    op.drop_table('meals')
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_history_date'))

    op.drop_table('meal_history')
    op.drop_table('user_preferences')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_off_barcode'))
        batch_op.drop_index(batch_op.f('ix_products_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_week_start'))

    op.drop_table('meal_plans')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
